# Generated by Django 4.1.3 on 2022-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionInquiry',
            fields=[
                ('ai_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('desertion_no', models.BigIntegerField(blank=True, null=True)),
                ('std_date', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'adoption_inquiry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikeStarPet',
            fields=[
                ('lp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('desertion_no', models.BigIntegerField(blank=True, null=True)),
                ('star', models.BigIntegerField(blank=True, null=True)),
                ('std_date', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'like_star_pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoaddogInfo',
            fields=[
                ('desertion_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('happen_dt', models.CharField(blank=True, max_length=100, null=True)),
                ('happen_place', models.CharField(blank=True, max_length=200, null=True)),
                ('kind_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('color_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.CharField(blank=True, max_length=200, null=True)),
                ('process_st', models.CharField(blank=True, max_length=100, null=True)),
                ('sex_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('neuter_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('special_mark', models.CharField(blank=True, max_length=200, null=True)),
                ('care_id', models.BigIntegerField()),
                ('label', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'roaddog_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('st_cd', models.BigIntegerField(primary_key=True, serialize=False)),
                ('care_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('care_tel', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('sigungu_cd', models.BigIntegerField()),
                ('care_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'shelter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('sido_cd', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sido_nm', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sigungu',
            fields=[
                ('sigungu_cd', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sigungu_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('sido_cd', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sigungu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('sv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('weight_cd', models.BigIntegerField(blank=True, null=True)),
                ('age_cd', models.BigIntegerField(blank=True, null=True)),
                ('attr_cd', models.BigIntegerField(blank=True, null=True)),
                ('health_cd', models.BigIntegerField(blank=True, null=True)),
                ('std_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
    ]
